// autogenerated via "yarn run build.js"
import { withPluginApi } from "discourse/lib/plugin-api";

function initIcons(api) {
  api.replaceIcon("anchor", "un-anchor");
  api.replaceIcon("angles-down", "un-angle-double-down");
  api.replaceIcon("angles-up", "un-angle-double-up");
  api.replaceIcon("bars", "un-bars");
  api.replaceIcon("bell", "un-bell");
  api.replaceIcon("bold", "un-bold");
  api.replaceIcon("bookmark", "un-bookmark");
  api.replaceIcon("briefcase", "un-briefcase-alt");
  api.replaceIcon("calendar-days", "un-calender");
  api.replaceIcon("caret-down", "un-angle-down");
  api.replaceIcon("caret-left", "un-angle-left");
  api.replaceIcon("caret-right", "un-angle-right");
  api.replaceIcon("caret-up", "un-angle-up");
  api.replaceIcon("certificate", "un-award");
  api.replaceIcon("chart-pie", "un-chart-pie");
  api.replaceIcon("circle-check", "un-check-circle");
  api.replaceIcon("check", "un-check");
  api.replaceIcon("square-check", "un-check-square");
  api.replaceIcon("chevron-down", "un-angle-down");
  api.replaceIcon("chevron-left", "un-angle-left");
  api.replaceIcon("chevron-right", "un-angle-right");
  api.replaceIcon("chevron-up", "un-angle-up");
  api.replaceIcon("clock", "un-clock");
  api.replaceIcon("code", "un-brackets-curly");
  api.replaceIcon("comments", "un-comments-alt");
  api.replaceIcon("gear", "un-cog");
  api.replaceIcon("comment", "un-comment-alt");
  api.replaceIcon("d-drop-collapsed", "un-angle-right");
  api.replaceIcon("d-drop-expanded", "un-angle-down");
  api.replaceIcon("d-liked", "un-heart");
  api.replaceIcon("d-muted", "un-bell-slash");
  api.replaceIcon("d-regular", "un-bell");
  api.replaceIcon("d-tracking", "un-bell");
  api.replaceIcon("d-unliked", "un-heart");
  api.replaceIcon("d-watching-first", "un-bell");
  api.replaceIcon("d-watching", "un-bell");
  api.replaceIcon("discourse-expand", "un-expand-alt");
  api.replaceIcon("download", "un-download-alt");
  api.replaceIcon("pen-to-square", "un-edit");
  api.replaceIcon("ellipsis", "un-ellipsis-h");
  api.replaceIcon("envelope", "un-envelope");
  api.replaceIcon("right-left", "un-arrows-h-alt");
  api.replaceIcon("far-circle-check", "un-check-circle");
  api.replaceIcon("far-eye-slash", "un-eye-slash");
  api.replaceIcon("far-eye", "un-eye");
  api.replaceIcon("far-image", "un-image");
  api.replaceIcon("far-trash-can", "un-trash-alt");
  api.replaceIcon("file", "un-file-alt");
  api.replaceIcon("filter", "un-filter");
  api.replaceIcon("flag", "un-asterisk");
  api.replaceIcon("folder-open", "un-folder-open");
  api.replaceIcon("folder", "un-folder");
  api.replaceIcon("heart", "un-heart");
  api.replaceIcon("house", "un-home-alt");
  api.replaceIcon("circle-info", "un-info-circle");
  api.replaceIcon("italic", "un-italic");
  api.replaceIcon("key", "un-key-skeleton");
  api.replaceIcon("layer-group", "un-layer-group");
  api.replaceIcon("link", "un-link-alt");
  api.replaceIcon("list-ol", "un-list-ol");
  api.replaceIcon("list-ul", "un-list-ul");
  api.replaceIcon("list", "un-list-ul");
  api.replaceIcon("lock", "un-lock");
  api.replaceIcon("notification.bookmark_reminder", "un-clock");
  api.replaceIcon("notification.edited", "un-edit");
  api.replaceIcon("notification.group_mentioned", "un-users-alt");
  api.replaceIcon("notification.group_message_summary", "un-users-alt");
  api.replaceIcon("notification.invited_to_private_message", "un-envelope");
  api.replaceIcon("notification.invited_to_topic", "un-arrow-right");
  api.replaceIcon("notification.invitee_accepted", "un-user");
  api.replaceIcon("notification.liked_2", "un-heart");
  api.replaceIcon("notification.liked_consolidated", "un-heart");
  api.replaceIcon("notification.liked_many", "un-heart");
  api.replaceIcon("notification.liked", "un-heart");
  api.replaceIcon("notification.linked", "un-link-alt");
  api.replaceIcon("notification.membership_request_accepted", "un-user-plus");
  api.replaceIcon(
    "notification.membership_request_consolidated",
    "un-users-alt"
  );
  api.replaceIcon("notification.mentioned", "un-at");
  api.replaceIcon("notification.post_approved", "un-check");
  api.replaceIcon("notification.posted", "un-corner-up-left");
  api.replaceIcon("notification.private_message", "un-envelope");
  api.replaceIcon("notification.reaction", "un-bell");
  api.replaceIcon("notification.replied", "un-corner-up-left");
  api.replaceIcon("notification.topic_reminder", "un-clock");
  api.replaceIcon("notification.votes_released", "un-plus");
  api.replaceIcon("notification.watching_first_post", "un-bell");
  api.replaceIcon("pencil", "un-edit");
  api.replaceIcon("plus", "un-plus");
  api.replaceIcon("quote-right", "un-feedback");
  api.replaceIcon("reply", "un-corner-up-left");
  api.replaceIcon("magnifying-glass", "un-search");
  api.replaceIcon("right-from-bracket", "un-signout");
  api.replaceIcon("face-smile", "un-smile");
  api.replaceIcon("bars-staggered", "un-align-center");
  api.replaceIcon("arrows-rotate", "un-sync");
  api.replaceIcon("circle-xmark", "un-times-circle");
  api.replaceIcon("xmark", "un-times");
  api.replaceIcon("toggle-off", "un-toggle-off");
  api.replaceIcon("toggle-on", "un-toggle-on");
  api.replaceIcon("trash-can", "un-trash-alt");
  api.replaceIcon("upload", "un-upload");
  api.replaceIcon("user-plus", "un-user-plus");
  api.replaceIcon("user", "un-user");
  api.replaceIcon("video", "un-video");
  api.replaceIcon("wrench", "un-wrench");
}

export default {
  name: "unicons",
  initialize() {
    withPluginApi("0.10.1", initIcons);
  },
};
